# Generated by Django 5.0.3 on 2024-04-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0004_profile1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=100)),
                ('work_type', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
            ],
        ),
    ]
