# Generated by Django 5.0.3 on 2024-04-29 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0005_jobmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='email',
            new_name='cemail',
        ),
        migrations.RenameField(
            model_name='jobmodel',
            old_name='experience',
            new_name='cexp',
        ),
        migrations.RenameField(
            model_name='jobmodel',
            old_name='job_title',
            new_name='cname',
        ),
        migrations.RenameField(
            model_name='jobmodel',
            old_name='job_type',
            new_name='ctitle',
        ),
        migrations.RenameField(
            model_name='jobmodel',
            old_name='username',
            new_name='ctype',
        ),
        migrations.RenameField(
            model_name='jobmodel',
            old_name='work_type',
            new_name='jtype',
        ),
    ]
